plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

packageExtensions:
  chalk@^5:
    dependencies:
      '#ansi-styles': 'npm:ansi-styles@6.1.0'
      '#supports-color': 'npm:supports-color@9.2.2'
